version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install -r requirements.txt # Install project dependencies
      # - pytest tests/                   # Run unit tests
  post_build:
    commands:
      echo "Post build"
artifacts:
  files: "**/*" # This depends on your project structure