version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Install dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - pytest

artifacts:
  files: '**/*'
  discard-paths: yes
